# Łączenie z bazą SQL

In [5]:
import pandas as pd

uniwersalny sposób dla różnych baz danych

Musimy się połączyć z naszą bazą danych. Do tego celu musimy znać typ bazy, nazwę użytkownika i hasło, localhost, port i nazwę bazy. W dokumentacji widzimy jak połączyć te informacje w zależności od naszej bazy:      
https://docs.sqlalchemy.org/en/latest/core/engines.html

Aby uzyskać dostęp do bazy i powyższe informacje skontaktuj się odpowiednim działem w twojej organizacji.

In [6]:
from sqlalchemy import create_engine
# see sqlalchemy docs for how to write this url for your database type:

In [8]:
engine = create_engine('postgresql+psycopg2://postgres:haslo@localhost:5432/dvdrental')

In [9]:
engine.table_names()

['staff',
 'category',
 'film_category',
 'country',
 'actor',
 'language',
 'inventory',
 'payment',
 'rental',
 'city',
 'store',
 'wiatr',
 'film',
 'address',
 'film_actor',
 'customer',
 'nowa_tabela',
 'dane_meteo_cisnienie2',
 'nowa nowa nowa',
 'imgw',
 'temperatury',
 'dane_meteo_cisnienie',
 'opady',
 'dane_meteo']

In [10]:
pd.read_sql("select * from film where release_year = 2006", engine)

,film_id,title,description,release_year,language_id,rental_duration,rental_rate,length,replacement_cost,rating,last_update,special_features,fulltext
0,133,Chamber Italian,A Fateful Reflection of a Moose And a Husband ...,2006,1,7,4.99,117,14.99,NC-17,2013-05-26 14:50:58.951,[Trailers],'chamber':1 'fate':4 'husband':11 'italian':2 ...
1,384,Grosse Wonderful,A Epic Drama of a Cat And a Explorer who must ...,2006,1,5,4.99,49,19.99,R,2013-05-26 14:50:58.951,[Behind the Scenes],'australia':18 'cat':8 'drama':5 'epic':4 'exp...
2,8,Airport Pollock,A Epic Tale of a Moose And a Girl who must Con...,2006,1,6,4.99,54,15.99,R,2013-05-26 14:50:58.951,[Trailers],'airport':1 'ancient':18 'confront':14 'epic':...
3,98,Bright Encounters,A Fateful Yarn of a Lumberjack And a Feminist ...,2006,1,4,4.99,73,12.99,PG-13,2013-05-26 14:50:58.951,[Trailers],'boat':20 'bright':1 'conquer':14 'encount':2 ...
4,1,Academy Dinosaur,A Epic Drama of a Feminist And a Mad Scientist...,2006,1,6,0.99,86,20.99,PG,2013-05-26 14:50:58.951,"[Deleted Scenes, Behind the Scenes]",'academi':1 'battl':15 'canadian':20 'dinosaur...
5,2,Ace Goldfinger,A Astounding Epistle of a Database Administrat...,2006,1,3,4.99,48,12.99,G,2013-05-26 14:50:58.951,"[Trailers, Deleted Scenes]",'ace':1 'administr':9 'ancient':19 'astound':4...
6,3,Adaptation Holes,A Astounding Reflection of a Lumberjack And a ...,2006,1,7,2.99,50,18.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Deleted Scenes]",'adapt':1 'astound':4 'baloon':19 'car':11 'fa...
7,4,Affair Prejudice,A Fanciful Documentary of a Frisbee And a Lumb...,2006,1,5,2.99,117,26.99,G,2013-05-26 14:50:58.951,"[Commentaries, Behind the Scenes]",'affair':1 'chase':14 'documentari':5 'fanci':...
8,5,African Egg,A Fast-Paced Documentary of a Pastry Chef And ...,2006,1,6,2.99,130,22.99,G,2013-05-26 14:50:58.951,[Deleted Scenes],'african':1 'chef':11 'dentist':14 'documentar...
9,6,Agent Truman,A Intrepid Panorama of a Robot And a Boy who m...,2006,1,3,2.99,169,17.99,PG,2013-05-26 14:50:58.951,[Deleted Scenes],'agent':1 'ancient':19 'boy':11 'china':20 'es...
10,7,Airplane Sierra,A Touching Saga of a Hunter And a Butler who m...,2006,1,6,4.99,62,28.99,PG-13,2013-05-26 14:50:58.951,"[Trailers, Deleted Scenes]","'airplan':1 'boat':20 'butler':11,16 'discov':..."
11,9,Alabama Devil,A Thoughtful Panorama of a Database Administra...,2006,1,3,2.99,114,21.99,PG-13,2013-05-26 14:50:58.951,"[Trailers, Deleted Scenes]",'administr':9 'alabama':1 'boat':23 'databas':...
12,10,Aladdin Calendar,A Action-Packed Tale of a Man And a Lumberjack...,2006,1,6,4.99,63,24.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Deleted Scenes]",'action':5 'action-pack':4 'aladdin':1 'ancien...
13,11,Alamo Videotape,A Boring Epistle of a Butler And a Cat who mus...,2006,1,6,0.99,126,16.99,G,2013-05-26 14:50:58.951,"[Commentaries, Behind the Scenes]",'alamo':1 'bore':4 'butler':8 'cat':11 'chef':...
14,12,Alaska Phantom,A Fanciful Saga of a Hunter And a Pastry Chef ...,2006,1,6,0.99,136,22.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes]",'alaska':1 'australia':19 'boy':17 'chef':12 '...
15,213,Date Speed,A Touching Saga of a Composer And a Moose who ...,2006,1,4,0.99,104,19.99,R,2013-05-26 14:50:58.951,[Commentaries],'compos':8 'convent':20 'date':1 'dentist':16 ...
16,13,Ali Forever,A Action-Packed Drama of a Dentist And a Croco...,2006,1,4,4.99,150,21.99,PG,2013-05-26 14:50:58.951,"[Deleted Scenes, Behind the Scenes]",'action':5 'action-pack':4 'ali':1 'battl':16 ...
17,14,Alice Fantasia,A Emotional Drama of a A Shark And a Database ...,2006,1,6,0.99,94,23.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Deleted Scenes, Behind the Scenes]",'administr':13 'alic':1 'databas':12 'drama':5...
18,15,Alien Center,A Brilliant Drama of a Cat And a Mad Scientist...,2006,1,5,2.99,46,10.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Behind the Scenes]",'alien':1 'battl':15 'brilliant':4 'cat':8 'ce...
19,16,Alley Evolution,A Fast-Paced Drama of a Robot And a Composer w...,2006,1,6,2.99,180,23.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Commentaries]",'alley':1 'astronaut':18 'battl':16 'compos':1...
20,17,Alone Trip,A Fast-Paced Character Study of a Composer And...,2006,1,3,0.99,82,14.99,R,2013-05-26 14:50:58.951,"[Trailers, Behind the Scenes]",'abandon':22 'alon':1 'boat':19 'charact':7 'c...
21,18,Alter Victory,A Thoughtful Drama of a Composer And a Feminis...,2006,1,6,0.99,57,27.99,PG-13,2013-05-26 14:50:58.951,"[Trailers, Behind the Scenes]",'agent':17 'alter':1 'canadian':20 'compos':8 ...
22,19,Amadeus Holy,A Emotional Display of a Pioneer And a Technic...,2006,1,6,0.99,113,20.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'amadeus':1 'baloon':20 'battl':15 'display':5...
23,20,Amelie Hellfighters,A Boring Drama of a Woman And a Squirrel who m...,2006,1,4,4.99,79,23.99,R,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'ameli':1 'baloon':19 'bore':4 'conquer':14 'd...
24,21,American Circus,A Insightful Drama of a Girl And a Astronaut w...,2006,1,3,4.99,129,17.99,R,2013-05-26 14:50:58.951,"[Commentaries, Behind the Scenes]",'administr':17 'american':1 'astronaut':11 'ci...
25,22,Amistad Midsummer,A Emotional Character Study of a Dentist And a...,2006,1,6,2.99,85,10.99,G,2013-05-26 14:50:58.951,"[Commentaries, Behind the Scenes]",'amistad':1 'california':20 'charact':5 'croco...
26,23,Anaconda Confessions,A Lacklusture Display of a Dentist And a Denti...,2006,1,3,0.99,92,9.99,R,2013-05-26 14:50:58.951,"[Trailers, Deleted Scenes]",'anaconda':1 'australia':18 'confess':2 'denti...
27,24,Analyze Hoosiers,A Thoughtful Display of a Explorer And a Pastr...,2006,1,6,2.99,181,19.99,R,2013-05-26 14:50:58.951,"[Trailers, Behind the Scenes]",'analyz':1 'chef':12 'desert':21 'display':5 '...
28,25,Angels Life,A Thoughtful Display of a Woman And a Astronau...,2006,1,3,2.99,74,15.99,G,2013-05-26 14:50:58.951,[Trailers],'angel':1 'astronaut':11 'battl':14 'berlin':1...
29,26,Annie Identity,A Amazing Panorama of a Pastry Chef And a Boat...,2006,1,3,0.99,86,15.99,G,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes]",'abandon':20 'amaz':4 'amus':21 'anni':1 'boat...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,971,Whale Bikini,A Intrepid Story of a Pastry Chef And a Databa...,2006,1,4,4.99,109,11.99,PG-13,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'administr':13 'bikini':2 'chef':9 'convent':2...
971,972,Whisperer Giant,A Intrepid Story of a Dentist And a Hunter who...,2006,1,4,4.99,59,24.99,PG-13,2013-05-26 14:50:58.951,"[Trailers, Deleted Scenes]",'ancient':18 'confront':14 'dentist':8 'giant'...
972,973,Wife Turn,A Awe-Inspiring Epistle of a Teacher And a Fem...,2006,1,3,4.99,183,27.99,NC-17,2013-05-26 14:50:58.951,"[Deleted Scenes, Behind the Scenes]",'ancient':20 'awe':5 'awe-inspir':4 'confront'...
973,974,Wild Apollo,A Beautiful Story of a Monkey And a Sumo Wrest...,2006,1,4,0.99,181,24.99,R,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Deleted Scenes, Behin...",'apollo':2 'beauti':4 'conquer':15 'convent':2...
974,975,Willow Tracy,A Brilliant Panorama of a Boat And a Astronaut...,2006,1,6,2.99,137,22.99,R,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Behind the Scenes]",'astronaut':11 'boat':8 'brilliant':4 'challen...
975,976,Wind Phantom,A Touching Saga of a Madman And a Forensic Psy...,2006,1,6,0.99,111,12.99,R,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes]",'abandon':21 'build':15 'forens':11 'madman':8...
976,977,Window Side,A Astounding Character Study of a Womanizer An...,2006,1,3,2.99,85,25.99,R,2013-05-26 14:50:58.951,"[Deleted Scenes, Behind the Scenes]",'astound':4 'charact':5 'escap':15 'hunter':12...
977,978,Wisdom Worker,A Unbelieveable Saga of a Forensic Psychologis...,2006,1,3,0.99,98,12.99,R,2013-05-26 14:50:58.951,"[Deleted Scenes, Behind the Scenes]",'face':15 'first':20 'forens':8 'man':21 'must...
978,979,Witches Panic,A Awe-Inspiring Drama of a Secret Agent And a ...,2006,1,6,4.99,100,10.99,NC-17,2013-05-26 14:50:58.951,"[Commentaries, Behind the Scenes]",'agent':11 'awe':5 'awe-inspir':4 'drama':7 'f...
979,980,Wizard Coldblooded,A Lacklusture Display of a Robot And a Girl wh...,2006,1,4,4.99,75,12.99,PG,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes, Behind the Scenes]",'coldblood':2 'convent':21 'defeat':14 'displa...
980,981,Wolves Desire,A Fast-Paced Drama of a Squirrel And a Robot w...,2006,1,7,0.99,55,13.99,NC-17,2013-05-26 14:50:58.951,[Behind the Scenes],'desir':2 'drama':7 'fast':5 'fast-pac':4 'man...
981,982,Women Dorado,A Insightful Documentary of a Waitress And a B...,2006,1,4,0.99,126,23.99,R,2013-05-26 14:50:58.951,"[Deleted Scenes, Behind the Scenes]",'australia':18 'butler':11 'compos':16 'docume...
982,983,Won Dares,A Unbelieveable Documentary of a Teacher And a...,2006,1,7,2.99,105,18.99,PG,2013-05-26 14:50:58.951,[Behind the Scenes],'boat':21 'dare':2 'defeat':14 'documentari':5...
983,984,Wonderful Drop,A Boring Panorama of a Woman And a Madman who ...,2006,1,3,2.99,126,20.99,NC-17,2013-05-26 14:50:58.951,[Commentaries],'boat':21 'bore':4 'butler':16 'drop':2 'madma...
984,985,Wonderland Christmas,A Awe-Inspiring Character Study of a Waitress ...,2006,1,4,4.99,111,19.99,PG,2013-05-26 14:50:58.951,[Commentaries],'awe':5 'awe-inspir':4 'car':14 'charact':7 'c...
985,986,Wonka Sea,A Brilliant Saga of a Boat And a Mad Scientist...,2006,1,6,2.99,85,24.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Commentaries]",'ancient':19 'boat':8 'brilliant':4 'india':20...
986,987,Words Hunter,A Action-Packed Reflection of a Composer And a...,2006,1,3,2.99,116,13.99,PG,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Deleted Scenes]",'action':5 'action-pack':4 'compos':10 'conven...
987,988,Worker Tarzan,A Action-Packed Yarn of a Secret Agent And a T...,2006,1,7,2.99,139,26.99,R,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Behind the Scenes]",'action':5 'action-pack':4 'agent':11 'battl':...
988,989,Working Microcosmos,A Stunning Epistle of a Dentist And a Dog who ...,2006,1,4,4.99,74,22.99,R,2013-05-26 14:50:58.951,"[Commentaries, Deleted Scenes]",'ancient':18 'china':19 'dentist':8 'dog':11 '...
989,990,World Leathernecks,A Unbelieveable Tale of a Pioneer And a Astron...,2006,1,3,0.99,171,13.99,PG-13,2013-05-26 14:50:58.951,"[Trailers, Behind the Scenes]",'abandon':19 'amus':20 'astronaut':11 'leather...
990,991,Worst Banger,A Thrilling Drama of a Madman And a Dentist wh...,2006,1,4,2.99,185,26.99,PG,2013-05-26 14:50:58.951,"[Deleted Scenes, Behind the Scenes]",'banger':2 'boy':16 'conquer':14 'dentist':11 ...
991,992,Wrath Mile,A Intrepid Reflection of a Technical Writer An...,2006,1,5,0.99,176,17.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Commentaries]",'defeat':15 'hunter':12 'intrepid':4 'mile':2 ...
992,993,Wrong Behavior,A Emotional Saga of a Crocodile And a Sumo Wre...,2006,1,6,2.99,178,10.99,PG-13,2013-05-26 14:50:58.951,"[Trailers, Behind the Scenes]",'behavior':2 'cow':18 'crocodil':8 'discov':15...
993,994,Wyoming Storm,A Awe-Inspiring Panorama of a Robot And a Boat...,2006,1,6,4.99,100,29.99,PG-13,2013-05-26 14:50:58.951,[Deleted Scenes],"'awe':5 'awe-inspir':4 'boat':13,23 'feminist'..."
994,995,Yentl Idaho,A Amazing Display of a Robot And a Astronaut w...,2006,1,5,4.99,86,11.99,R,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Deleted Scenes]",'amaz':4 'astronaut':11 'berlin':18 'display':...
995,996,Young Language,A Unbelieveable Yarn of a Boat And a Database ...,2006,1,6,0.99,183,9.99,G,2013-05-26 14:50:58.951,"[Trailers, Behind the Scenes]",'administr':12 'boat':8 'boy':17 'databas':11 ...
996,997,Youth Kick,A Touching Drama of a Teacher And a Cat who mu...,2006,1,4,0.99,179,14.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Behind the Scenes]",'boat':22 'cat':11 'challeng':14 'drama':5 'ki...
997,998,Zhivago Core,A Fateful Yarn of a Composer And a Man who mus...,2006,1,6,0.99,105,10.99,NC-17,2013-05-26 14:50:58.951,[Deleted Scenes],'boy':16 'canadian':19 'compos':8 'core':2 'fa...
998,999,Zoolander Fiction,A Fateful Reflection of a Waitress And a Boat ...,2006,1,5,2.99,101,28.99,R,2013-05-26 14:50:58.951,"[Trailers, Deleted Scenes]",'ancient':19 'boat':11 'china':20 'discov':14 ...
999,1000,Zorro Ark,A Intrepid Panorama of a Mad Scientist And a B...,2006,1,3,4.99,50,18.99,NC-17,2013-05-26 14:50:58.951,"[Trailers, Commentaries, Behind the Scenes]","'ark':2 'boy':12,17 'intrepid':4 'mad':8 'mona..."

In [15]:
table_name = 'actor'
df = pd.read_sql(table_name, engine)

In [16]:
# Wysyłamy query do bazy i jako wynik otrzymujemy obiekt DataFrames
df = pd.read_sql("SELECT last_name, first_name FROM actor", engine)

In [19]:
df.to_sql("nowa_tabela2", engine)

In [20]:
# Tabele w naszej bazie
engine.table_names()

['staff',
 'category',
 'film_category',
 'country',
 'actor',
 'language',
 'inventory',
 'payment',
 'rental',
 'city',
 'store',
 'wiatr',
 'film',
 'address',
 'film_actor',
 'customer',
 'nowa_tabela',
 'dane_meteo_cisnienie2',
 'nowa_tabela2',
 'nowa nowa nowa',
 'imgw',
 'temperatury',
 'dane_meteo_cisnienie',
 'opady',
 'dane_meteo']

In [32]:
# Zapisujemy do bazy SQL (pod warunkiem że mamy uprawnienia do tworzenia nowych tabel)
df.to_sql("nowa nowa nowa",engine)

In [33]:
engine.table_names()

['staff',
 'category',
 'film_category',
 'country',
 'actor',
 'language',
 'inventory',
 'payment',
 'rental',
 'city',
 'store',
 'film',
 'address',
 'film_actor',
 'customer',
 'nowa nowa nowa']

In [34]:
# Wczytujemy całą tabelę
pd.read_sql("nowa nowa nowa", engine)

     index     last_name first_name
0        0       Guiness   Penelope
1        1      Wahlberg       Nick
2        2         Chase         Ed
3        3         Davis   Jennifer
4        4  Lollobrigida     Johnny
5        5     Nicholson      Bette
6        6        Mostel      Grace
7        7     Johansson    Matthew
8        8         Swank        Joe
9        9         Gable  Christian
10      10          Cage       Zero
11      11         Berry       Karl
12      12          Wood        Uma
13      13        Bergen     Vivien
14      14       Olivier       Cuba
15      15       Costner       Fred
16      16        Voight      Helen
17      17          Torn        Dan
18      18       Fawcett        Bob
19      19         Tracy    Lucille
20      20       Paltrow    Kirsten
21      21          Marx      Elvis
22      22        Kilmer     Sandra
23      23        Streep    Cameron
24      24         Bloom      Kevin
25      25      Crawford        Rip
26      26       Mcqueen      Julia
27      27       Hoffman      Woody
28      28         Wayne       Alec
29      29          Peck     Sandra
..     ...           ...        ...
170    170      Pfeiffer    Olympia
171    171      Williams    Groucho
172    172      Dreyfuss       Alan
173    173        Bening    Michael
174    174       Hackman    William
175    175         Chase        Jon
176    176      Mckellen       Gene
177    177        Monroe       Lisa
178    178       Guiness         Ed
179    179   Silverstone       Jeff
180    180        Carrey    Matthew
181    181        Akroyd     Debbie
182    182         Close    Russell
183    183       Garland   Humphrey
184    184        Bolger    Michael
185    185     Zellweger      Julia
186    186          Ball      Renee
187    187       Dukakis       Rock
188    188         Birch       Cuba
189    189        Bailey     Audrey
190    190       Gooding    Gregory
191    191        Suvari       John
192    192        Temple       Burt
193    193         Allen      Meryl
194    194   Silverstone      Jayne
195    195        Walken       Bela
196    196          West      Reese
197    197        Keitel       Mary
198    198       Fawcett      Julia
199    199        Temple      Thora

[200 rows x 3 columns]

### Wykonujemy query bez fetch (bez pobierania danych do pythona)

In [21]:
engine.execute("SELECT * FROM actor")

In [23]:
engine.execute("DROP TABLE nowa_tabela2")

In [24]:
engine.table_names()

['staff',
 'category',
 'film_category',
 'country',
 'actor',
 'language',
 'inventory',
 'payment',
 'rental',
 'city',
 'store',
 'wiatr',
 'film',
 'address',
 'film_actor',
 'customer',
 'nowa_tabela',
 'dane_meteo_cisnienie2',
 'nowa nowa nowa',
 'imgw',
 'temperatury',
 'dane_meteo_cisnienie',
 'opady',
 'dane_meteo']